trigger:
  branches:
    include:
    - dev
  paths:
    include:
    - front/todo-app/*
    exclude:
    - README.md
    - front/todo-app/README.md
    - front/todo-app/.gitignore

pr:
  branches:
    include:
    - dev
  paths:
    include:
    - front/todo-app/*
    exclude:
    - README.md
    - front/todo-app/README.md
    - front/todo-app/.gitignore    

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd front/todo-app
    npm install
    npm run build
  displayName: 'npm install and build'
