trigger:
  branches:
    include:
    - ci-playground-of-death
    exclude:
    - '*'
  paths:
    include:
    - front/**/*
    exclude:
    - README.md
    - front/todo-app/README.md
    - front/todo-app/.gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd front/todo-app
    npm install
    npm run build
  displayName: 'npm install and build'
